version: '1.0'

services:
  db:
    image: mysql:8.0
    # platform: linux/amd64
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_DATABASE: gpmlogin_db
      # MYSQL_ROOT_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Cho phép mật khẩu trống
    volumes:
      - mysql_data:/var/lib/mysql
      - ./gpmlogin.sql:/docker-entrypoint-initdb.d/gpmlogin.sql

  app:
    build: .
    image: giaiphapmmo/gpm-login-private-server:1.0  # Tên và phiên bản của image
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    depends_on:
      - db

volumes:
  mysql_data: