version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "${WEB_PORT:-80}:80"
        volumes:
            # - '.:/var/www/html'
            - 'web_storage:/var/www/html/storage'
            - './docker/php/php_large_file_upload.ini:/usr/local/etc/php/conf.d/php_large_file_upload.ini'
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        networks:
            - laravel-network
    mysql:
        image: 'mysql/mysql-server:8.0'
        # ports:
        #     - '${FORWARD_DB_PORT:-3306}:3306'
        restart: unless-stopped
        environment:
            # MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './gpmlogin.sql:/docker-entrypoint-initdb.d/gpmlogin.sql'
        networks:
            - laravel-network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: unless-stopped
        ports:
            - "8081:80"
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        networks:
            - laravel-network
        depends_on:
            - mysql
networks:
    laravel-network:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    web_storage:
        driver: local
